name: Deploy to EC2 with Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy app files to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          mkdir -p ${{ secrets.DEPLOY_PATH }}
        EOF

        scp -o StrictHostKeyChecking=no \
        app.py requirements.txt Dockerfile docker-compose.yml \
        ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.DEPLOY_PATH }}


    - name: Run Docker Compose on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e
          cd ${{ secrets.DEPLOY_PATH }}
          docker-compose down || true
          docker-compose up -d --build
        EOF
